/*
 * addPackage.java
 *
 * Created on January 5, 2017, 6:57 PM
 */

package mansa;


import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Date;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author  User
 */
public class addCustomers extends javax.swing.JFrame {
    String selectedpackage;
    
    /** Creates new form addPackage */
    public addCustomers() {
        initComponents();
        
        txtAddress.setText("");
        txtBill.setText("");
        txtName.setText("");
        txtTele.setText("");
        txtid.setText("");
        cPackage.setSelectedIndex(0);
        txtAge.setText("");
        txtHeight.setText("");
        
            try {
                
                Connection c=DB.mycon();
                Statement s=c.createStatement();
                ResultSet rs=s.executeQuery("SELECT * FROM `package` WHERE 1");
                while(rs.next()){
                
                   cPackage.addItem(rs.getString("name")+"-"+rs.getString("price"));
                }
                
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
      
        
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBill = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTele = new javax.swing.JTextField();
        cPackage = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        startDate = new com.toedter.calendar.JDateChooser();
        expDate = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(204, 0, 0));
        txtName.setText("jTextField1");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Address : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(204, 0, 0));
        txtAddress.setText("jTextField1");
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 220, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Exp Date : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Meb. No : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBill.setForeground(new java.awt.Color(204, 0, 0));
        txtBill.setText("txt");
        txtBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillActionPerformed(evt);
            }
        });
        jPanel1.add(txtBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 220, 30));

        lblimage.setBackground(new java.awt.Color(153, 153, 153));
        lblimage.setText("Image");
        jPanel1.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 160, 170));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Telephone : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        txtTele.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTele.setForeground(new java.awt.Color(204, 0, 0));
        txtTele.setText("jTextField1");
        txtTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleActionPerformed(evt);
            }
        });
        jPanel1.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 220, 30));

        cPackage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cPackage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select the Package" }));
        jPanel1.add(cPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 220, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Select the Package : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Start Date : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("REGISTER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 130, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setText("SEARCH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 130, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Add Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(51, 51, 255));
        txtid.setText("txtid");
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 220, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 204));
        jButton7.setText("DELETE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 130, 40));
        jPanel1.add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 220, 30));
        jPanel1.add(expDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 220, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Age : ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(204, 0, 0));
        txtAge.setText("txt");
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 220, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Height : ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        txtHeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHeight.setForeground(new java.awt.Color(204, 0, 0));
        txtHeight.setText("txt");
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        jPanel1.add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 880, 380));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add New Member");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 0, 0));
        jButton8.setText("HOME");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, 130, 60));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("MANSA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 50));

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fittness");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backg.jpg"))); // NOI18N
        jLabel5.setText("hjjh");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1036, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    if(empty() && empty2() && empty3() && phone() && age()){
    try {
 
        Date a=startDate.getDate();
        String date=a.toString();
        String ar[]=date.split(" ");
        String newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
        
        Date a1=expDate.getDate();
        String date1=a1.toString();
        String ar1[]=date1.split(" ");
        String newdate1=ar1[5]+"-"+ar1[1]+"-"+ar1[2];
        
        
        int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to add this Member...");
        if(x==0){
              //jFileChooser1.showOpenDialog(this);
       File f=jFileChooser1.getSelectedFile();
       String path=f.getAbsolutePath();
       
       path =path.replace("\\", "/");
        
            Connection c=DB.mycon();
            Statement s=c.createStatement();
            s.executeUpdate(" INSERT INTO `customer`(`IdNo`, `membershipNO`, `name`, `telephone`, `address`, `package`, `startdate`, `expiredate`, `image`, `age`, `height`) VALUES ( '"+txtid.getText()+"','"+txtBill.getText()+"','"+txtName.getText()+"','"+txtTele.getText()+"','"+txtAddress.getText()+"','"+cPackage.getSelectedItem().toString()+"','"+newdate+"','"+newdate1+"','"+path+"', '"+txtAge.getText()+"','"+txtHeight.getText()+"' ) ");
            
            JOptionPane.showMessageDialog(rootPane, "New Member Added successfully");
            
            
            new Payment(txtName.getText(),txtAddress.getText(),txtid.getText(),cPackage.getSelectedItem().toString(),txtTele.getText()).setVisible(true);
             //  new Payment().setVisible(true);
             this.dispose();
        txtAddress.setText("");
        txtBill.setText("");
        txtName.setText("");
        txtTele.setText("");
        txtid.setText("");
        cPackage.setSelectedIndex(0);
        txtAge.setText("");
        txtHeight.setText("");
        lblimage.setIcon(null);
        }
         else if(x==1){
        txtAddress.setText("");
        txtBill.setText("");
        txtName.setText("");
        txtTele.setText("");
        txtAge.setText("");
        txtHeight.setText("");
        cPackage.setSelectedIndex(0);
        }
                
        
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Please add member photo");
        e.printStackTrace();
    }
   }  
}//GEN-LAST:event_jButton5ActionPerformed

private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNameActionPerformed

private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtAddressActionPerformed

private void txtBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtBillActionPerformed

private void txtTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtTeleActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    try {
        
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery(" SELECT * FROM `customer` WHERE IdNo='"+txtid.getText()+"' ");
        if(rs.next()){
        
 
       File f1=new File (rs.getString("image"));
       Image im=ImageIO.read(f1);
       im=im.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
       lblimage.setIcon(new ImageIcon(im));
     
            
            txtid.setText(rs.getString("IdNo"));
            txtAddress.setText(rs.getString("address"));
            txtName.setText(rs.getString("name"));
            txtBill.setText(rs.getString("membershipNO"));
            txtTele.setText(rs.getString("telephone"));
              txtAge.setText(rs.getString("age"));
                txtHeight.setText(rs.getString("height"));
            cPackage.setSelectedItem(rs.getString("package"));
            String a=rs.getString("startdate");
            String b=rs.getString("expiredate");
           SimpleDateFormat date=new SimpleDateFormat("yyyy-MMM-d");
           startDate.setDate(date.parse(a));
           expDate.setDate(date.parse(b));
        }
        else{
        JOptionPane.showMessageDialog(rootPane, "There is no member from this NIC!!!!");
        }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
       new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    try {
        
        jFileChooser1.showOpenDialog(this);
       File f=jFileChooser1.getSelectedFile();
       String path=f.getAbsolutePath();
       
       path =path.replace("\\", "/");
       File f1=new File (path);
       Image im=ImageIO.read(f1);
       im=im.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
       lblimage.setIcon(new ImageIcon(im));
       
       
       
       
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtidActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    try {
        int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to delete this member??");
        if(x==0){
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        s.executeUpdate("DELETE FROM `customer` WHERE IdNo='"+txtid.getText()+"'");
        
        JOptionPane.showMessageDialog(rootPane, "Member Deleted sucessfully...");
        
           txtAddress.setText("");
        txtBill.setText("");
        txtName.setText("");
        txtTele.setText("");
        txtid.setText("");
         txtHeight.setText("");

        txtAge.setText("");
        cPackage.setSelectedIndex(0);
        lblimage.setIcon(null);
        }
         else if(x==1){
        txtAddress.setText("");
        txtBill.setText("");
        txtName.setText("");
        txtTele.setText("");
        cPackage.setSelectedIndex(0);
        }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton7ActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    /**
    * @param args the command line arguments
    */
    
    public boolean nic() {
	Pattern p=Pattern.compile("^[0-9]{9}[vVxX]$");
	Matcher m=p.matcher(txtid.getText());
	if(m.matches()){
		return true;
	}
	else{
	JOptionPane.showMessageDialog(rootPane, "invalid NIC"); 	
   	return false; 
	}
    }
    public boolean empty() {
	if(txtAddress.getText().isEmpty() || txtAge.getText().isEmpty() || txtBill.getText().isEmpty() || txtHeight.getText().isEmpty() || txtName.getText().isEmpty() || txtTele.getText().isEmpty() || txtid.getText().isEmpty()){
		
            JOptionPane.showMessageDialog(rootPane, "Field cannot empty"); 
            return false;
	}
	else{
		
   	return true; 
	}
    }
    public boolean empty2() {
	if(cPackage.getSelectedIndex()==0){
		JOptionPane.showMessageDialog(rootPane, "select package"); 	
                return false; 
	}
	else{
	return true;
	}
    }
     public boolean empty3() {
	if(startDate.getDate()==null || expDate.getDate()==null){
		JOptionPane.showMessageDialog(rootPane, "select date"); 	
                return false;
	}
	else{
	  return true;
	}
    }
    public boolean phone() {
	Pattern p=Pattern.compile("[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]");
	Matcher m=p.matcher(txtTele.getText());
	if(m.matches()){
		return true;
	}
	else{
	JOptionPane.showMessageDialog(rootPane, "invalid phone number.\nEnter 10 digit PHONE N0."); 	
   	return false; 
	}
    }
    public boolean age() {
	Pattern p=Pattern.compile("[0-9][0-9]");
	Matcher m=p.matcher(txtAge.getText());
	if(m.matches()){
		return true;
	}
	else{
	JOptionPane.showMessageDialog(rootPane, "invalid age.\nEnter 2 digit age."); 	
   	return false; 
	}
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cPackage;
    private com.toedter.calendar.JDateChooser expDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblimage;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBill;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTele;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

}
