/*
 * addPackage.java
 *
 * Created on January 5, 2017, 6:57 PM
 */

package mansa;


import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.io.File;
/**
 *
 * @author  User
 */
public class searchCostomer extends javax.swing.JFrame {
   
      String newdate;
    /** Creates new form addPackage */
    public searchCostomer() {
        initComponents();
       
       
     
         try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
           newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
          
           lbldate.setText(newdate);
           
           
                    }
                
                }
            }).start();
        
            
        } catch (Exception e) {
            e.printStackTrace();
        }
      
    updateTableS();
  
    }
      public void  updateTableS() {
        try {
        
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        ResultSet rs= s.executeQuery("SELECT * FROM `customer` WHERE expiredate='"+lbldate.getText()+"'");
        
       while(rs.next()){
           
             
                DefaultTableModel a=(DefaultTableModel)table1.getModel();
                a.addRow(new Object[] {rs.getString("name"),rs.getString("telephone")});
               
              
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    }
    public void  clearTable() {
    
               DefaultTableModel aj=(DefaultTableModel)table1.getModel();
    
                 while(aj.getRowCount() > 0){
    
                         for(int i=0;i<aj.getRowCount();i++){
                        aj.removeRow(i);
                        }
                  }
    
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblname = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jButton8 = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        lblimage = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Expired Membership");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblname.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TODAY IS : ");
        lblname.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lbldate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldate.setForeground(new java.awt.Color(153, 0, 0));
        lbldate.setText("jLabel1");
        lblname.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Enter the Expire Date you want  : ");
        lblname.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        date1.setDateFormatString("  yyyy-MMM-d");
        lblname.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 220, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 0, 0));
        jButton8.setText("SEARCH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        lblname.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 100, 40));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtName.setText("jTextField1");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        lblname.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 120, 30, 30));

        table1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table1.setForeground(new java.awt.Color(0, 51, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Telephone"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        table1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        lblname.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 500, 210));

        lblimage.setText("Image");
        lblname.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 160, 170));

        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 880, 370));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 0, 0));
        jButton9.setText("HOME");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 130, 70));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("MANSA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 50));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fittness");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backg.jpg"))); // NOI18N
        jLabel5.setText("hjjh");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1036, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
      
       Date a1=date1.getDate();
        String date1=a1.toString();
        String ar1[]=date1.split(" ");
        String newdate1=ar1[5]+"-"+ar1[1]+"-"+ar1[2];
    clearTable();
    
          try {
        
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        ResultSet rs= s.executeQuery("SELECT * FROM `customer` WHERE expiredate='"+newdate1+"'");
        
       while(rs.next()){
       
                DefaultTableModel a=(DefaultTableModel)table1.getModel();
                a.addRow(new Object[] {rs.getString("name"),rs.getString("telephone"),rs.getString("name")});
               
              
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
 
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// TODO add your handling code here:
      new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton9ActionPerformed

private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNameActionPerformed

private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
// TODO add your handling code here:
    DefaultTableModel model=(DefaultTableModel)table1.getModel();
    int x=table1.getSelectedRow();
    txtName.setText(model.getValueAt(x, 0).toString());
    
     try {
        
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery(" SELECT * FROM `customer` WHERE name='"+txtName.getText()+"' ");
        while(rs.next()){
        
 
       File f1=new File (rs.getString("image"));
       Image im=ImageIO.read(f1);
       im=im.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
       lblimage.setIcon(new ImageIcon(im));
     
            
        } 
     
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    
}//GEN-LAST:event_table1MouseClicked

private void table1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table1KeyPressed
// TODO add your handling code here:
     DefaultTableModel model=(DefaultTableModel)table1.getModel();
    int x=table1.getSelectedRow();
    txtName.setText(model.getValueAt(x, 0).toString());
    
     try {
        
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery(" SELECT * FROM `customer` WHERE name='"+txtName.getText()+"' ");
        while(rs.next()){
        
 
       File f1=new File (rs.getString("image"));
       Image im=ImageIO.read(f1);
       im=im.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
       lblimage.setIcon(new ImageIcon(im));
     
            
        } 
     
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}//GEN-LAST:event_table1KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchCostomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblimage;
    private javax.swing.JPanel lblname;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
