/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mansa;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class updatepayment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public updatepayment() {
        initComponents();
        date();
        txtAddress.disable();
        txtName.disable();
        txtBalance.disable();
        txtpackage.disable();
        pdate.setEnabled(false);
        
        
    }
    String newdate;
    public updatepayment(String name,String address,String nic,String pAmount){
         initComponents();
         
        date();
            
    
        
         System.out.println(newdate);
         
         
         String string = pAmount;
        String[] parts = string.split("-");
        String part2 = parts[1];
        
        System.out.println(lblDate.getText());
        txtAddress.setText(address);
        txtName.setText(name);
        txtNic.setText(nic);
        txtpackage.setText(part2);
    
    }

    public void date(){
        try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
           newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
          
           lblDate1.setText(newdate);
           
           
                    }
                
                }
            }).start();
        
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpackage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblbalance = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        pdate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Mem Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 220, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Package Amt : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtpackage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpackage.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtpackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Payment : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(204, 0, 0));
        txtBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtBalanceMouseReleased(evt);
            }
        });
        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        txtBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBalanceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBalanceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBalanceKeyTyped(evt);
            }
        });
        jPanel1.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 220, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Address : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("NIC : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        txtNic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNic.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 220, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Balance :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        lblbalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblbalance.setText("0.00");
        jPanel1.add(lblbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("Update Payment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 160, 30));
        jPanel1.add(pdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 220, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Exp Date :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 760, 250));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fittness");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("MANSA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 50));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Member Payment");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblDate1.setText("jLabel11");
        getContentPane().add(lblDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 80, -1));

        lblDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backg.jpg"))); // NOI18N
        lblDate.setText("hjjh");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Connection c=DB.mycon();
            Statement s=c.createStatement();
            ResultSet rs=s.executeQuery(" SELECT * FROM `payment` WHERE NIC='"+txtNic.getText()+"' ");
            if(empty()){
            if(!rs.next()){
                
                JOptionPane.showMessageDialog(rootPane, "No Such a Person From This NIC!");
            }
            else{
            
                txtAddress.setText(rs.getString("address"));
            txtName.setText(rs.getString("name"));
            txtpackage.setText(rs.getString("pamount"));
            txtBalance.setText(rs.getString("paid"));
              lblbalance.setText(rs.getString("balance"));
              //pdate.Date(date.parse(a));
              txtName.enable();
        txtAddress.enable();
        txtBalance.enable();
        txtpackage.enable();
        pdate.setEnabled(true);
            }
            }
        }
         catch (Exception e) {
             System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(empty2() && balance()){
        try {
        int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to update this data??");
        
        if(x==0){
        Date a=pdate.getDate();
            String date=a.toString();
            String ar[]=date.split(" ");
            String newdate=ar[5]+"-"+ar[1]+"-"+ar[2]; 
            String month=ar[1];
            
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("Select * from payment where NIC='"+txtNic.getText()+"'");
        if(rs.next()){
            Double paid1=Double.parseDouble(rs.getString("paid"))+Double.parseDouble(txtBalance.getText());
            s.executeUpdate(" UPDATE `payment` SET `balance`='"+lblbalance.getText()+"',paid='"+paid1+"',pdate='"+lblDate1.getText()+"', `balanceEDate`='"+newdate+"',`ExpMonth`='"+month+"' WHERE NIC='"+txtNic.getText()+"' ");
        }
        
        
       
        JOptionPane.showMessageDialog(rootPane, "Data successfully Updated..");
       
        txtAddress.setText("");
        txtBalance.setText("");
        txtName.setText("");
        txtNic.setText("");
        txtpackage.setText("");
        lblbalance.setText("");;
                
        }
        else{
        txtAddress.setText("");
        txtBalance.setText("");
        txtName.setText("");
        txtNic.setText("");
        txtpackage.setText("");
        lblbalance.setText("");;
        }
        
        
        } catch (Exception e) {
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtBalanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyPressed
        // TODO add your handling code here:
           
         
    }//GEN-LAST:event_txtBalanceKeyPressed

    private void txtBalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyReleased
        // TODO add your handling code here:
 
    }//GEN-LAST:event_txtBalanceKeyReleased

    private void txtBalanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceKeyTyped

    private void txtBalanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBalanceMouseReleased
          // TODO add your handling code here:
           
    }//GEN-LAST:event_txtBalanceMouseReleased

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
        if(empty1() && balance()){
            double balance=0;
            balance=(Double.parseDouble(lblbalance.getText()))-(Double.parseDouble(txtBalance.getText()));
            lblbalance.setText(Double.toString(balance));
        }
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean empty() {
	
	if(txtNic.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Enter NIC"); 
        return false;
        }
        else{
        return true;
        }
    }
    public boolean empty2() {
	
	if(txtNic.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Search the employee first!!!!"); 
        return false;
        }
        else{
        return true;
        }
    }
     public boolean balance() {
	Pattern p=Pattern.compile("-?\\d+(.\\d+)?");
	Matcher m=p.matcher(txtBalance.getText());
	
	if(m.matches()){
		return true;
	}
	else{
	JOptionPane.showMessageDialog(rootPane, "invalid value for balance"); 	
   	return false; 
	}
    }
    public boolean empty1() {
	
	if(txtBalance.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "balanace field cannot be empty"); 
        return false;
        }
        else{
        return true;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatepayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatepayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatepayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatepayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatepayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblbalance;
    private com.toedter.calendar.JDateChooser pdate;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtpackage;
    // End of variables declaration//GEN-END:variables
}
